# Generated by Django 5.2 on 2025-07-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_stockholding_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockholding',
            options={'ordering': ['stock_symbol', 'purchase_date']},
        ),
        migrations.AlterUniqueTogether(
            name='stockholding',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
