# Generated by Django 5.2.6 on 2025-11-18 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRepriceStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_shares', models.DecimalField(decimal_places=4, max_digits=19)),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('market_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('strategy_mode', models.CharField(choices=[('shares', 'Shares'), ('price', 'Target Price')], max_length=10)),
                ('strategy_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
