# Generated by Django 5.2.6 on 2026-03-04 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_savedrebalancescenario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcapitalgainsscenario',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='savedcapitalgainsscenario',
            name='result_data',
        ),
        migrations.RemoveField(
            model_name='savedrebalancescenario',
            name='categories_data',
        ),
        migrations.RemoveField(
            model_name='savedrebalancescenario',
            name='holdings_data',
        ),
        migrations.AddField(
            model_name='savedcapitalgainsscenario',
            name='asset_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedcapitalgainsscenario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgs_scenarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedrebalancescenario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalance_scenarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedrepricestrategy',
            name='average_price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='savedrepricestrategy',
            name='current_shares',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='savedrepricestrategy',
            name='market_price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='savedrepricestrategy',
            name='strategy_value',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.CreateModel(
            name='CGSPurchaseLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('fees', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lots', to='calculators.savedcapitalgainsscenario')),
            ],
        ),
        migrations.CreateModel(
            name='CGSResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_gain_loss', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_sale_proceeds', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('estimated_tax', models.DecimalField(decimal_places=2, max_digits=19)),
                ('net_gain_loss', models.DecimalField(decimal_places=2, max_digits=19)),
                ('holding_period', models.CharField(max_length=50)),
                ('gain_loss_type', models.CharField(max_length=50)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calculators.savedcapitalgainsscenario')),
            ],
        ),
        migrations.CreateModel(
            name='CGSSaleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('fees', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='calculators.savedcapitalgainsscenario')),
            ],
        ),
        migrations.CreateModel(
            name='CGSTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(choices=[('UK', 'UK'), ('US', 'US')], max_length=10)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=19)),
                ('filing_status', models.CharField(blank=True, max_length=20, null=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='calculators.savedcapitalgainsscenario')),
            ],
        ),
        migrations.CreateModel(
            name='RebalanceCategoryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_percent', models.IntegerField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_targets', to='calculators.savedrebalancescenario')),
            ],
        ),
        migrations.CreateModel(
            name='RebalanceHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('category', models.CharField(max_length=100)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='calculators.savedrebalancescenario')),
            ],
        ),
    ]
