# Generated by Django 5.2.6 on 2026-03-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0004_remove_savedcapitalgainsscenario_input_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebalanceholding',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='savedrebalancescenario',
            name='user',
        ),
        migrations.DeleteModel(
            name='RebalanceCategoryTarget',
        ),
        migrations.DeleteModel(
            name='RebalanceHolding',
        ),
        migrations.DeleteModel(
            name='SavedRebalanceScenario',
        ),
    ]
