# Generated by Django 5.2.6 on 2026-03-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0005_remove_rebalanceholding_scenario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrepricestrategy',
            name='strategy_mode',
            field=models.CharField(choices=[('shares', 'Shares'), ('price', 'Target Price'), ('tranches', 'Simulator')], max_length=10),
        ),
        migrations.AlterField(
            model_name='savedrepricestrategy',
            name='strategy_value',
            field=models.TextField(),
        ),
    ]
