# Generated by Django 5.2.6 on 2026-03-09 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0006_alter_savedrepricestrategy_strategy_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDRIPProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initial_principal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('annual_contribution', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dividend_yield_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('annual_appreciation_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('years_to_grow', models.IntegerField()),
                ('final_balance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_dividends', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drip_projections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
